server:
  port: 9001

spring:
  application:
    name: customer-provider
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT&&rewriteBatchedStatements=true
      username: root
      password: 010818lt

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.edu.goodscommons.domain

#指定当前服务注册的"服务注册发现中心"的地址
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka