server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    #    是否注入到eureka中，因为这是中心，所以不必
    register-with-eureka: false
    #    是否到服务中心获取应用地址
    fetch-registry: false
    #    设置注册的地址  http://ip:port/eureka
    service-url:
      defaultzone: http://localhost:8761/eureka